Completed CRUD actions for Register Apps
praveenyr/crushmet pull request #2
Opened 2017-07-09 16:20 UTC by praveenyr

**Description:** Completed CRUD actions for _Register Apps_  user story.

**Test Coverage:** 95.79%

2017-07-09 18:55 UTC, brittanyjspringer requested changes

2017-07-09 18:55 UTC, wonderwoman13 commented on app/assets/javascripts/registered_applications.coffee
> +# Place all the behaviors and hooks related to the matching controller here.
@praveenyr this is not being used so please remove.

2017-07-09 18:55 UTC, wonderwoman13 commented on app/assets/stylesheets/registered_applications.scss
> +// Place all the styles related to the RegisteredApplications controller here.
@praveenyr this is not being used so please remove.

2017-07-09 18:55 UTC, wonderwoman13 commented on coverage/.last_run.json
> +{
@praveenyr please add /coverage/* to your .gitignore file and delete the coverage folder.

2017-07-09 18:55 UTC, wonderwoman13 commented on spec/helpers/registered_applications_helper_spec.rb
> +
@praveenyr this is not being used so please remove.

2017-07-10 16:06 UTC, praveenyr commented
@wonderwoman13  - all set.

2017-07-10 17:15 UTC, brittanyjspringer approved these changes

2017-07-10 17:15 UTC, merged